name: Build solution

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            10.0.x

      - name: Restore
        run: dotnet restore MicroserviceApp.sln

      - name: Build
        run: dotnet build MicroserviceApp.sln --no-restore -c Release
